# Part of Odoo. See LICENSE file for full copyright and licensing details. 
{
    'name': 'Sale To Mrp',
    'version': '12.0.1.4 26-jun',
    'author': 'Prime Minds',
    'website': "https://primeminds.co/",
    'description': """This module will send mail to the portal users""",
    'category': 'Tools',
    'depends': ['base',
                'sale', 
                # 'web_editor',
                # 'website_sale',
                # 'website_profile',
                'account',
                'mrp',
                'mrp_workorder',
                'quality_control',
                'sales_team',
                'sale_management',
                'purchase',
                'purchase_stock',
                'sale_crm',
                'product',],
    'data': [
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'views/work_order_view.xml',
        'views/mrp_view_inherit.xml',
        'views/sale_view_inherited.xml',
        'views/payment_inherit.xml',
        'views/sale_performa_invoice.xml',
        'views/quality_view.xml',
        'data/ir_sequence_data.xml',
        'views/purchase_view.xml',
        'views/stock_quant_inherit.xml',
        'views/sale_portal_templates.xml',
        'views/journal_entry.xml',
    ],
    'installable': True,
    'auto_install': False,
}
